### ISSUE TITLE
Logging directory not found or is not absolute path.	search►

### ISSUE THREAD

**Issue by nobicycle** [sphido/cms#13]
Hello and thanks for Sphido.
Install goes well but on opening in the browser (chromium, vivaldi)  I get:
"Logging directory not found or is not absolute path."

I attach a pdf of that webpage.

Regards 

[Uploading RuntimeException_ Logging directory not found or is not absolute path_.pdf…]()
[RuntimeException_ Logging directory not found or is not absolute path_.txt](https://github.com/sphido/cms/files/257720/RuntimeException_.Logging.directory.not.found.or.is.not.absolute.path_.txt)

**Comment by OzzyCzech** [comment]
There is missing log directory. `mkdir log` or remove `rm -rf vendor/tracy` from project will help.

**Comment by austinvernsonger** [comment]
Do you need anymore Contributors?
